### ISSUE TITLE
Remote image hosting

### ISSUE THREAD

**Issue by perry** [fwenzel/upshot#30]
Being able to push the images up to s3, imgur, or similar services would be great. My biggest gripe with the Dropbox backend is that when you delete the images from your folder the link is broken.

**Comment by joostrijneveld** [comment]
Given the observations in #71, you asserted that this has become a more important feature. It seems that SFTP and SCP are typically easier to implement than third party protocols. When relying on preconfigured SSH keys being in place, an SCP call should not be much more difficult than moving a file to Dropbox' public folder. Perhaps it makes sense to give that priority.

**Comment by fwenzel** [comment]
Thank you, this is a very good point. Work on this is progressing well. The hardest part is in fact splitting up the architecture of the app to enable multiple delivery mechanisms. That said you're right that API calls with OAuth etc. are a lot harder than a simple scp call.

I might in fact start a wiki on this repository that has information on what you need to do to make certain things work. It could explain ssh keys and such, so the actual app UI can remain simple.

**Comment by joostrijneveld** [comment]
I recognise that actually building infrastructure to allow for a 'simple SCP call' is what will require the most effort. That said, I agree with your idea of writing instructions rather than including things like SSH authentication in the app itself. There's something to be said for doing one thing and doing it right. Perhaps rather than a wiki, this would be something for the README.md, so as to be more noticable. I suppose it depends on the verbosity and number of different alternatives what the best style is.
